<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.1 static/car2.gltf
-->

<script>
	import { speed } from '$lib/stores';
	import { Group } from 'three';
	import { T, forwardEventHandlers, useFrame } from '@threlte/core';
	import { useGltf, useGltfAnimations, useInteractivity } from '@threlte/extras';
	import { onMount } from 'svelte';
	import { radian } from '$lib/utils';

	export const ref = new Group();

	const gltf = useGltf('/car_red.gltf');
	export const { actions, mixer } = useGltfAnimations(gltf, ref);

	const component = forwardEventHandlers();

	let wheelRotation = 0;

	const wheelDiameter = 0.6; // meters
	$: wheelRotationPerSec = ($speed * 1000) / 3600 / (wheelDiameter * Math.PI); // calc speed in m/s, then divide by wheel circumference

	useFrame((_, delta) => {
		if (delta != 0) wheelRotation += radian(wheelRotationPerSec / 1 / delta);
	});

	useInteractivity();
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component} castShadow>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Group name="Scene">
			<T.Group name="body" position={[0, -0.05, 0]}>
				<T.Mesh name="Mesh" geometry={gltf.nodes.Mesh.geometry} material={gltf.materials.parts} />
				<T.Mesh
					name="Mesh_1"
					geometry={gltf.nodes.Mesh_1.geometry}
					material={gltf.materials.hl_glass}
				/>
				<T.Mesh
					name="Mesh_2"
					geometry={gltf.nodes.Mesh_2.geometry}
					material={gltf.materials.mirrors}
				/>
				<T.Mesh
					name="Mesh_3"
					geometry={gltf.nodes.Mesh_3.geometry}
					material={gltf.materials.windows}
				/>
				<T.Mesh
					name="Mesh_4"
					geometry={gltf.nodes.Mesh_4.geometry}
					material={gltf.materials.body}
				/>
			</T.Group>
			<T.Mesh
				name="leds_f"
				geometry={gltf.nodes.leds_f.geometry}
				material={gltf.materials.leds_f}
				position={[0, -0.05, 0]}
			/>
			<T.Mesh
				name="turning_light_l"
				geometry={gltf.nodes.turning_light_l.geometry}
				material={gltf.materials.orange_lights}
				position={[0, -0.05, 0]}
			/>
			<T.Mesh
				name="leds_r"
				geometry={gltf.nodes.leds_r.geometry}
				material={gltf.materials.leds_rear}
				position={[0, -0.05, 0]}
			/>
			<T.Mesh
				name="turning_light_r"
				geometry={gltf.nodes.turning_light_r.geometry}
				material={gltf.materials.orange_lights}
				position={[0, -0.05, 0]}
			/>
			<T.Mesh
				name="lights"
				geometry={gltf.nodes.lights.geometry}
				material={gltf.materials.parts}
				position={[0, -0.05, 0]}
			/>
			<T.Mesh
				name="brake_lights"
				geometry={gltf.nodes.brake_lights.geometry}
				material={gltf.materials.leds_rear}
				position={[0, -0.05, 0]}
			/>
			<T.Mesh
				name="rim-fl"
				geometry={gltf.nodes['rim-fl'].geometry}
				material={gltf.materials.rim}
				position={[0.86, 0.33, 1.53]}
				rotation.x={wheelRotation}
			/>
			<T.Mesh
				name="disk-fl"
				geometry={gltf.nodes['disk-fl'].geometry}
				material={gltf.materials['tire-brakes']}
				position={[0.79, 0.33, 1.53]}
			/>
			<T.Mesh
				name="caliper-fl"
				geometry={gltf.nodes['caliper-fl'].geometry}
				material={gltf.materials['tire-brakes']}
				position={[0.78, 0.39, 1.41]}
			/>
			<T.Mesh
				name="tire1-fl"
				geometry={gltf.nodes['tire1-fl'].geometry}
				material={gltf.materials['tire-brakes']}
				position={[0.8, 0.33, 1.53]}
				rotation.x={wheelRotation}
			/>
			<T.Mesh
				name="caliper-rl"
				geometry={gltf.nodes['caliper-rl'].geometry}
				material={gltf.materials['tire-brakes']}
				position={[0.78, 0.39, -1.47]}
			/>
			<T.Mesh
				name="disk-rl"
				geometry={gltf.nodes['disk-rl'].geometry}
				material={gltf.materials['tire-brakes']}
				position={[0.79, 0.33, -1.35]}
			/>
			<T.Mesh
				name="rim-rl"
				geometry={gltf.nodes['rim-rl'].geometry}
				material={gltf.materials.rim}
				position={[0.86, 0.33, -1.35]}
				rotation.x={wheelRotation}
			/>
			<T.Mesh
				name="tire1-rl"
				geometry={gltf.nodes['tire1-rl'].geometry}
				material={gltf.materials['tire-brakes']}
				position={[0.8, 0.33, -1.35]}
				rotation.x={wheelRotation}
			/>
			<T.Mesh
				name="caliper-rr"
				geometry={gltf.nodes['caliper-rr'].geometry}
				material={gltf.materials['tire-brakes']}
				position={[-0.78, 0.39, -1.23]}
			/>
			<T.Mesh
				name="caliper-fr"
				geometry={gltf.nodes['caliper-fr'].geometry}
				material={gltf.materials['tire-brakes']}
				position={[-0.78, 0.39, 1.65]}
			/>
			<T.Mesh
				name="disk-rr"
				geometry={gltf.nodes['disk-rr'].geometry}
				material={gltf.materials['tire-brakes']}
				position={[-0.79, 0.33, -1.35]}
			/>
			<T.Mesh
				name="disk-fr"
				geometry={gltf.nodes['disk-fr'].geometry}
				material={gltf.materials['tire-brakes']}
				position={[-0.79, 0.33, 1.53]}
			/>
			<T.Mesh
				name="rim-rr"
				geometry={gltf.nodes['rim-rr'].geometry}
				material={gltf.materials.rim}
				position={[-0.86, 0.33, -1.35]}
				rotation.x={wheelRotation}
			/>
			<T.Mesh
				name="rim-fr"
				geometry={gltf.nodes['rim-fr'].geometry}
				material={gltf.materials.rim}
				position={[-0.86, 0.33, 1.53]}
				rotation.x={wheelRotation}
			/>
			<T.Mesh
				name="tire1-rr"
				geometry={gltf.nodes['tire1-rr'].geometry}
				material={gltf.materials['tire-brakes']}
				position={[-0.8, 0.33, -1.35]}
				rotation.x={wheelRotation}
			/>
			<T.Mesh
				name="tire1-fr"
				geometry={gltf.nodes['tire1-fr'].geometry}
				material={gltf.materials['tire-brakes']}
				position={[-0.8, 0.33, 1.53]}
				rotation.x={wheelRotation}
			/>
		</T.Group>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
